[project]
name = "mcqa-bench"
version = "0.1.0"
description = "MCQA Benchmark Project"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.1.1",
    "inspect-ai>=0.3.132",
    "pandas>=2.3.2",
    "python-dotenv>=1.1.1",
    "scipy>=1.15.3",
]
